### ISSUE TITLE
Roadmap for v2.0

### ISSUE THREAD

**Issue by librehat** [librehat/yapstocks#1]
- [x] Tooltips showing more information (still limited) when hovered on the symbol or name
 - [x] Asset information shown in an overlay 
 - [x] Tooltips showing today's open price, yesterday's close price, day high and day low when hovered on the price or price change
 - [x] Historical prices chart in an overlay 
 - [x] Add GPLv3 banner to all source code files
 - [x] Show `+` for positive price changes

**Comment by librehat** [comment]
Information page (equities):

 - Statistics
   - Fiscal Year
     - Fiscal Year Ends
     - Most Recent Quarter
   - Stock Price History
     - Beta
     - 52-Week Change
     - 52-Week High
     - 52-Week Low
     - 50-Day Moving Average
     - 200-Day Moving Average
   - Dividends
     - Forward Annual Dividend (Rate & Yield)
     - Trailing Annual Dividend (Rate & Yield)
     - Dividend Date
     - Ex-Dividend Date
 - Company Profile (if not `null`, on a separate tab)
   - Address
   - Website
   - Sector
   - Industry
   - Fulltime employees
   - Key Executives
   - Description (this can be very long)

For indices, only components (top 30).

**Comment by librehat** [comment]
All features are implemented
